---
title: "Blunt-nosed Leopard Lizard Conceptual Diagram Plots"
author: "Savannah Weaver"
output: 
  rmarkdown::html_vignette:
    highlight: tango
    thumbnails: FALSE
    toc: TRUE
    toc_depth: 3
---






# Packages

```{r setup, echo=T, results='hide', message=FALSE}
if (!require("tidyverse")) install.packages("tidyverse") 
library("tidyverse") # for tidy/dplyr workflow of calculations
if (!require("ggplot2")) install.packages("ggplot2")
library("ggplot2") # plots
if (!require("RColorBrewer")) install.packages("RColorBrewer")
library("RColorBrewer") # pretty colors
if (!require("ggpubr")) install.packages("ggpubr")
library("ggpubr") # for multi-ggplot figs
```



# Create Fake Data

```{r}
df <- data.frame(x = c(1, 2, 3, 1, 2, 3),
                 y = c(1, 2, 3, 3, 2, 1),
                 group = c("A", "A", "A", "B", "B", "B")
                 )
df

cola <- brewer.pal(11, "RdYlBu")[c(10)]
colb <- brewer.pal(11, "RdYlBu")[c(2)]
colors <- c(colb, cola)
```




# Plot CEWL ~ VPD

```{r}
ggplot(df) + 
  aes(x = x,
      y = y,
      color = group) +
  geom_line(alpha = 1,
            size = 1.5) + 
  scale_color_manual(values = colors) + 
  labs(x = "VPD",
       y = "CEWL") +
  xlim(0.8, 3.2) +
  ylim(0.8, 3.2) +
  theme_classic() + 
  annotate(geom = "text", x = 2.9, y = 3.15, label = "physics", size = 3) +
  annotate(geom = "text", x = 2.9, y = 0.85, label = "physiology", size = 3) +
  theme(text = element_text(color = "black", 
                            family = "sans", 
                            size = 12),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none") -> CEWL_VPD_diagram
CEWL_VPD_diagram
```




# Plot CEWL ~ Osmolality

```{r}
ggplot(df) + 
  aes(x = x,
      y = y,
      color = group) +
  geom_line(alpha = 1,
            size = 1.5) + 
  scale_color_manual(values = colors) + 
  labs(x = "Plasma Osmolality",
       y = "CEWL") +
  xlim(0.8, 3.2) +
  ylim(0.8, 3.2) +
  theme_classic() + 
  annotate(geom = "text", x = 2.8, y = 3.15, label = "dehydration", size = 3) +
  annotate(geom = "text", x = 2.8, y = 0.85, label = "conservation", size = 3) +
  theme(text = element_text(color = "black", 
                            family = "sans", 
                            size = 12),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none") -> CEWL_osml_diagram
CEWL_osml_diagram
```















# Group & Export

```{r}
# arrange together
ggarrange(CEWL_VPD_diagram,
          CEWL_osml_diagram,
          ncol = 1, nrow = 2,
          legend = "none"
          ) -> CEWL_diagram

# export figure
ggsave(filename = "CEWL_diagram.pdf",
       plot = CEWL_diagram,
       path = "./results_figures",
       device = "pdf",
       dpi = 600,
       units = "mm",
       width = 60, height = 100)
```


















